### ISSUE TITLE
google.assistant.embedded.v1alpha2

### ISSUE THREAD

**Issue by polokoio456** [mautini/google-assistant-java-demo#4]
Hi :
Google Assistant SDK Version is upgrade from v1alpha1 to v1alpha2 now.
Do you think about this demo to update to v1alpha2 ?

Thanks.

**Comment by mautini** [comment]
Yes, I saw the release. If I have time, I will do it for sure :)

**Comment by mautini** [comment]
Hi,

I updated the code for the v1alpha2 (version 0.2.0). It doesn't support all the new features of the alpha2 but you can use it right now.

I close the issue

**Comment by polokoio456** [comment]
Thank you very much.
