### ISSUE TITLE
its not working .. 

### ISSUE THREAD

**Issue by islamHeralla** [mautini/google-assistant-java-demo#7]
While parsing a protocol message, the input ended unexpectedly in the middle of a field. This could mean either that the input has been truncated or that an embedded message misreported its own length

**Comment by islamHeralla** [comment]
that's the error i got ..
BTW i used it for the past 3 weeks .. it was perfect now it stopped working for some reason

**Comment by mautini** [comment]
Hi, sorry for the very (very) late response. I just updated the project and it works now
